// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocufmtilyesighcxoans.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jdWZtdGlseWVzaWdoY3hvYW5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3ODIyMDYsImV4cCI6MjA2NTM1ODIwNn0.k4hOfmOMkUNo47-A7EqPwbPLU-MtsKpY6whg22aizZM";

console.log('🔍 SUPABASE_URL:', SUPABASE_URL)
console.log('🔍 SUPABASE_ANON_KEY:', SUPABASE_PUBLISHABLE_KEY ? 'EXISTS' : 'EMPTY');

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);